export enum ValidateErrorsConstant {
	AVATAR_ERROR = "AVATAR_ERROR",
	USERNAME_ERROR = "USERNAME_ERROR",
	FIRST_NAME = "FIRST_NAME",
	LAST_NAME = "LAST_NAME",
	AGE_ERROR = "AGE_ERROR",
	CITY_ERROR = "CITY_ERROR",
	CURRENCY_ERROR = "CURRENCY_ERROR",
	COUNTRY_ERROR = "COUNTRY_ERROR"
}
