name: Lint
run-name: branch ${{ github.ref_name }} commit ${{ github.workflow_sha }} runner ${{ github.actor }}
on:
    workflow_dispatch:
    pull_request:
        branches:
            - master
    push:
        branches:
            - dev
jobs:
    prepare:
        name: Prepare
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.2
              with:
                  node-version: 20
            - name: Setup Yarn
              uses: threeal/setup-yarn-action@v2.0.0
              with:
                  version: latest
    lintTs:
        name: Lint TypeScript
        runs-on: ubuntu-latest
        needs: prepare
        concurrency:
            group: lint
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.2
              with:
                  node-version: 20
            - name: Setup Yarn
              uses: threeal/setup-yarn-action@v2.0.0
              with:
                  version: latest
            - name: Lint style
              run: yarn lint:style
    lintStyle:
        name: Lint Style
        runs-on: ubuntu-latest
        needs: prepare
        concurrency:
            group: lint
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.2
              with:
                  node-version: 20
            - name: Setup Yarn
              uses: threeal/setup-yarn-action@v2.0.0
              with:
                  version: latest
            - name: Lint style
              run: yarn lint:style
