name: Ui Test
run-name: Workflow ${{ github.workflow }}; Branch ${{ github.ref_name }}; Runner ${{ github.actor }}
on:
    workflow_dispatch:
    pull_request:
        branches:
            - master
            - dev
        paths-ignore:
            - .github/**/*
            - ./**/*.json
            - .stylelintrc.js
            - .stylelintignore
            - .eslintignore
            - .gitignore
            - .prettierignore
            - README.md
            - yarn.lock
            - config/**/*
            - webpack.config.ts
jobs:
    prepare:
        name: Prepare
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.2
            - name: Setup Yarn
              uses: threeal/setup-yarn-action@v2.0.0
              with:
                  version: latest
    testUi:
        name: Ui Test
        runs-on: ubuntu-latest
        needs: prepare
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.2
              with:
                  fetch-depth: 0
            - name: Setup Yarn
              uses: threeal/setup-yarn-action@v2.0.0
              with:
                  version: latest
            - name: Run Chromatic
              uses: chromaui/action@latest
              with:
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
