name: Unit Test
run-name: ${{ github.workflow }}; Trigger ${{ github.ref_name }}; Runner ${{ github.actor }}
on:
    workflow_dispatch:
    pull_request:
        paths-ignore:
            - .github/**/*
            - ./**/*.json
            - .stylelintrc.js
            - .stylelintignore
            - .eslintignore
            - .gitignore
            - .prettierignore
            - README.md
            - yarn.lock
            - config/**/*
            - webpack.config.ts
jobs:
    prepare:
        name: Prepare
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.2
            - name: Setup Yarn
              uses: threeal/setup-yarn-action@v2.0.0
              with:
                  version: latest
    unitTest:
        name: Unit Test
        runs-on: ubuntu-latest
        needs: prepare
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.2
            - name: Setup Yarn
              uses: threeal/setup-yarn-action@v2.0.0
              with:
                  version: latest
            - name: test
              run: yarn test:unit
