name: Ui Test
run-name: Workflow ${{ github.workflow }}; Branch ${{ github.ref_name }}; Runner ${{ github.actor }}
on:
    workflow_dispatch:
    pull_request:
        branches:
            - master
    push:
        branches:
            - dev
        paths-ignore:
            - ".github/**"
            - "README.md"
jobs:
    prepare:
        name: Prepare
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.2
              with:
                  node-version: 20.x.x
            - name: Setup Yarn
              uses: threeal/setup-yarn-action@v2.0.0
              with:
                  version: latest
    testUi:
        name: Ui Test
        runs-on: ubuntu-latest
        needs: prepare
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.2
              with:
                  node-version: 20.x.x
            - name: Setup Yarn
              uses: threeal/setup-yarn-action@v2.0.0
              with:
                  version: latest
            - name: build storybook
              run: yarn storybook:build
            - name: test
              run: yarn test:ui:ci
